### ISSUE TITLE
Is this a collection of tools for Delphi for game developers?

### ISSUE THREAD

**Issue by Coldzer0** [tinyBigGAMES/DelphiGameKit#2]
Hello @jarroddavis68 

If yes, I would love to share my work to help Pascal game developers.

https://github.com/Coldzer0/ImGui-Pascal

This is an ImGui binding for Delphi / FPC

**Comment by jarroddavis68** [comment]
Hi! This repository is dedicated to a 2D game library I'm developing. I've checked your Imgui-pascal project – excellent work there! I've followed and starred it. There's indeed a pressing need to bring more attention to Pascal game development libraries and tools. Initially, I hadn't thought of starting a new list, given the awesome-pascal list's existence. However, I believe there's room for more collective efforts in this area. I'm very open to any suggestions you might have.
