### ISSUE TITLE
Audio is not working

### ISSUE THREAD

**Issue by Jayandi** [tinyBigGAMES/DelphiGamekit#7]
music_play project, played and no sound is produced

I added audio.getmusicvolume(FMusic) and the value is 0

========editted procedure========
procedure TExample.OnRenderHud;
var
  S : Single;
begin
  inherited;

  S := Audio.GetMusicVolume(FMusic);
  Hud.Text(DefaultFont, GREEN, haLeft, S.ToString, []);
end;

**Comment by jarroddavis68** [comment]
Hi, change the audio value on the line belove, from 0.5 to 1.0 and then go down 0.9, 0.8 etc. until you do not hear anything and let me know.
 
```Pascal
  FMusic := Audio.LoadPlayMusic(Archive, 'arc/music/song01.ogg', 0.5, -1, False);
```
I get audio on my end. I may need to adjust the scalar method I am using to calculate the final audio value to send to SDL.

Also, can you download the compiled examples and see if you can hear the audio?

Thanks.

**Comment by Jayandi** [comment]
It works after I copied first the data.arc file to my compiled folder where music_play.exe is. (getvolumemusic also shown as 

Interestingly, it doesn't work when I played from music_play.exe where all examples files are unzipped. 

So I think the Audio.loadplaymusic() takes the file from archive not folder instead.
Later I put a text to show the getmusicvolume value. When I set volume 1.0, it showed 1 and when I set 0.8, it showed 0.3125.

**Comment by jarroddavis68** [comment]
I see. Ok, I just checked LoadMusic and I need to make a few changes that did not get changed over. The new logic for loading resources is now:
- check if Archive is nil, then try to load from filesystem
- check if Archive is open, try to load from archive
- if Archive is not nil, but is not open, then try to load from filesystem.

With this logic, you will be able to transparently load from archive or the filesystem without having to change your file paths in your code.

These changes will be in an upcoming commit.

Ok, cool, thanks for reporting, I appreciate it. 👍🏿

**Comment by Jayandi** [comment]
Thank you Jarrod.
